# Generated by Django 5.0.6 on 2024-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimoregym", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="gymuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="gymuser",
            name="cognome",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="nome",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="gymuser",
            name="codice_fiscale",
            field=models.CharField(default="", max_length=16),
        ),
    ]
