# Generated by Django 5.0.6 on 2024-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "unimoregym",
            "0002_alter_gymuser_managers_gymuser_cognome_gymuser_nome_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymuser",
            name="data_nascita",
            field=models.DateField(default=""),
        ),
    ]
