# Generated by Django 5.0.6 on 2024-06-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimoregym", "0004_alter_gymuser_data_nascita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymuser",
            name="data_nascita",
            field=models.DateField(blank=True, null=True),
        ),
    ]
