# Generated by Django 5.0.6 on 2024-06-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimoregym", "0007_abbonamentiattivi_data_scadenza_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corso",
            name="categoria",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sessionecorso",
            name="disponibilita",
            field=models.IntegerField(default=30),
        ),
    ]
