# Generated by Django 5.0.6 on 2024-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimoregym", "0008_corso_categoria_sessionecorso_disponibilita"),
    ]

    operations = [
        migrations.AddField(
            model_name="corso",
            name="durata",
            field=models.IntegerField(default=60, help_text="Durata in minuti"),
        ),
    ]
