# Generated by Django 5.0.6 on 2024-06-25 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimoregym", "0009_corso_durata"),
    ]

    operations = [
        migrations.AddField(
            model_name="corso",
            name="valutazione_media",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stelle", models.IntegerField()),
                ("commento", models.TextField(blank=True, null=True)),
                (
                    "corso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="unimoregym.corso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("corso", "user")},
            },
        ),
    ]
